name: hookrail-redis

services:
  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - hookrail-redis-data:/data

  srh:
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: example_token
      SRH_CONNECTION_STRING: redis://redis:6379
    ports:
      - "8079:80"
    depends_on:
      - redis

volumes:
  hookrail-redis-data:
